# Generated by Django 4.2.16 on 2024-11-12 02:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('FORD', 'FORD'), ('FIAT', 'FIAT'), ('TOYOTA', 'TOYOTA'), ('CHEVROLET', 'CHEVROLET')], default='FORD', max_length=20)),
                ('modelo', models.TextField(max_length=100)),
                ('serial_carroceria', models.TextField(max_length=50)),
                ('serial_motor', models.TextField(max_length=50)),
                ('categoria', models.CharField(choices=[('PARTICULAR', 'PARTICULAR'), ('CARGA', 'CARGA'), ('TRANSPORTE', 'TRANSPORTE')], default='PARTICULAR', max_length=20)),
                ('precio', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2024, 11, 11, 23, 19, 31, 993566))),
                ('fecha_modificacion', models.DateTimeField(default=datetime.datetime(2024, 11, 11, 23, 19, 31, 993678))),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehículos',
                'permissions': [('visualizar_catalogo', 'Puede visualizar Catálogo de Vehículos'), ('development', 'Permiso como Desarrollador'), ('scrum_master', 'Permiso como Scrum Master'), ('product_owner', 'Permiso como Product Owner')],
            },
        ),
    ]
