# Generated by Django 4.2.16 on 2024-11-13 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='categoria',
            field=models.CharField(choices=[('TRANSPORTE', 'TRANSPORTE'), ('PARTICULAR', 'PARTICULAR'), ('CARGA', 'CARGA')], default='PARTICULAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 12, 22, 33, 18, 521945)),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_modificacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 12, 22, 33, 18, 522053)),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(choices=[('FORD', 'FORD'), ('FIAT', 'FIAT'), ('CHEVROLET', 'CHEVROLET'), ('TOYOTA', 'TOYOTA')], default='FORD', max_length=20),
        ),
    ]
